# Generated by Django 6.0.6 on 2026-09-24 09:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bootcamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان دوره")),
                (
                    "slug",
                    models.SlugField(
                        help_text="فقط حروف انگلیسی، عدد و خط تیره. مثال: python-summer",
                        max_length=160,
                        unique=True,
                        verbose_name="آدرس صفحه (Slug)",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرعنوان کوتاه"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="برای کارت دوره در صفحه\u200cی لیست دوره\u200cها استفاده می\u200cشود.",
                        max_length=400,
                        verbose_name="توضیح کوتاه",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="برای صفحه\u200cی اختصاصی دوره استفاده می\u200cشود.",
                        verbose_name="توضیح کامل",
                    ),
                ),
                (
                    "syllabus",
                    models.TextField(
                        blank=True,
                        help_text="هر سرفصل را در یک خط جدا وارد کنید.",
                        verbose_name="سرفصل\u200cها",
                    ),
                ),
                ("teacher", models.CharField(max_length=50, verbose_name="نام مدرس")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bootcamps/covers/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="برای دوره\u200cی رایگان، صفر بگذارید.",
                        verbose_name="قیمت (تومان)",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="مدت دوره (هفته)"
                    ),
                ),
                (
                    "sessions_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="تعداد جلسات در هفته"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ظرفیت ثبت\u200cنام"
                    ),
                ),
                (
                    "remaining_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        default=models.PositiveIntegerField(
                            blank=True, null=True, verbose_name="ظرفیت ثبت\u200cنام"
                        ),
                        null=True,
                        verbose_name="ظرفیت ثبت\u200cنام باقیمانده",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        default=True, verbose_name="ثبت\u200cنام باز است"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "بوت\u200cکمپ",
                "verbose_name_plural": "بوت\u200cکمپ\u200cها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.IntegerField(unique=True, verbose_name="شماره جلسه"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک ویدیو"),
                ),
                (
                    "chat_url",
                    models.URLField(
                        blank=True, default="", null=True, verbose_name="لینک چت زنده"
                    ),
                ),
                ("is_live", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "bootcamp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.bootcamp",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت\u200cنام",
                "verbose_name_plural": "ثبت\u200cنام\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="signatures/", verbose_name="عکس امضا"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="سن",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن صحیح نیست، حتما با اعداد انگلیسی وارد کنید.",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کدملی",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="ایمیل وارد شده صحیح نیست"
                            )
                        ],
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="رمز عبور"
                    ),
                ),
                (
                    "reshte",
                    models.CharField(
                        max_length=50, verbose_name="رشته تحصیلی دانشگاه/پایه مدرسه"
                    ),
                ),
                (
                    "school",
                    models.CharField(max_length=200, verbose_name="دانشگاه/مدرسه"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                (
                    "moaref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نحوه آشنایی با بوتکمپ",
                    ),
                ),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "certificate_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="مدرک نهایی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "bootcamps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        through="core.Enrollment",
                        to="core.bootcamp",
                        verbose_name="دوره\u200cهای ثبت\u200cنام\u200cشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانشجو",
                "verbose_name_plural": "دانشجویان",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(max_length=50, verbose_name="کد پیگیری"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_request",
                        to="core.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.student",
                verbose_name="دانشجو",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "bootcamp")},
        ),
    ]
