# Generated by Django 6.0.6 on 2026-07-04 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='سن')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('reshte', models.CharField(max_length=50, verbose_name='رشته تحصیلی')),
                ('school', models.CharField(max_length=200, verbose_name='دانشگاه/مدرسه')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('moaref', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
                'ordering': ['-created_at'],
            },
        ),
    ]
