# Generated by Django 6.0.6 on 2026-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(unique=True, verbose_name='شماره جلسه')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو')),
            ],
            options={
                'verbose_name': 'لینک ویدیو',
                'verbose_name_plural': 'لینک\u200cهای ویدیو',
            },
        ),
    ]
