# Generated by Django 6.0.6 on 2026-09-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrequest",
            name="student",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="certificates/",
                verbose_name="فایل مدرک",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_issued_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ صدور"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_certified",
            field=models.BooleanField(default=False, verbose_name="مدرک صادر شد"),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="enrollment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_request",
                to="core.enrollment",
                verbose_name="ثبت\u200cنام",
            ),
        ),
        migrations.AlterField(
            model_name="bootcamp",
            name="syllabus",
            field=models.TextField(blank=True, verbose_name="سرفصل\u200cها"),
        ),
        migrations.AlterField(
            model_name="student",
            name="certificate_file",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="chat_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="session_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="شماره جلسه")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان جلسه")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("online", "آنلاین"),
                            ("offline", "آفلاین"),
                            ("in_person", "حضوری"),
                        ],
                        default="online",
                        max_length=12,
                        verbose_name="نوع جلسه",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ برگزاری")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک ویدیو/پخش"
                    ),
                ),
                (
                    "chat_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک چت"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="آدرس (برای حضوری)"
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(default=False, verbose_name="در حال پخش زنده"),
                ),
                (
                    "bootcamp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.bootcamp",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه",
                "verbose_name_plural": "جلسات",
                "ordering": ["number"],
                "unique_together": {("bootcamp", "number")},
            },
        ),
    ]
