# Generated by Django 6.0.6 on 2026-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='moaref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نحوه آشنایی با بوتکمپ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reshte',
            field=models.CharField(max_length=50, verbose_name='رشته تحصیلی دانشگاه/پایه مدرسه'),
        ),
    ]
