# Generated by Django 6.0.6 on 2026-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_paymentrequest_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="certificate_fee",
            field=models.PositiveIntegerField(
                default=0,
                help_text="صفر یعنی مدرک رایگان. اگه پر باشه، کاربر می\u200cتونه بعداً مدرک بخره.",
                verbose_name="هزینه صدور مدرک (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_fee_paid",
            field=models.PositiveIntegerField(
                default=0, verbose_name="هزینه\u200cی پرداخت\u200cشده مدرک"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="with_certificate",
            field=models.BooleanField(
                default=False, verbose_name="ثبت\u200cنام با مدرک"
            ),
        ),
    ]
