# Generated by Django 6.0.6 on 2026-07-25 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_email_alter_student_moaref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='ایمیل وارد شده صحیح نیست')], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن صحیح نیست، حتما با اعداد انگلیسی وارد کنید.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
