# Generated by Django 6.0.6 on 2026-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='chat_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='لینک چت زنده'),
        ),
    ]
