# Generated by Django 6.0.6 on 2026-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bootcamp_certificate_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="certificate_template",
            field=models.ImageField(
                blank=True,
                help_text="اگه خالی بمونه، از تمپلیت پیش\u200cفرض استفاده می\u200cشه.",
                null=True,
                upload_to="certificate_templates/",
                verbose_name="تمپلیت مدرک",
            ),
        ),
        migrations.AlterField(
            model_name="bootcamp",
            name="sessions_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="تعداد جلسات"
            ),
        ),
    ]
