# Generated by Django 6.0.6 on 2026-07-25 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_password_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن صحیح نیست، حتما با اعداد انگلیسی وارد کنید.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
