# Generated by Django 6.0.6 on 2026-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videolink_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
