# Generated by Django 6.0.6 on 2026-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bootcamp_certificate_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="برای دوره\u200cهای پولی تا تأیید پرداخت False می\u200cمونه.",
                verbose_name="ثبت\u200cنام فعال",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="registration_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تأیید پرداخت ثبت\u200cنام"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="registration_tracking_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="کد پیگیری پرداخت ثبت\u200cنام",
            ),
        ),
    ]
