# Generated by Django 6.0.6 on 2026-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_videolink_is_live'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolink',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کدملی'),
        ),
    ]
