# Generated by Django 6.0.6 on 2026-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_videolink_options_student_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
