# Generated by Django 6.0.6 on 2026-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_enrollment_is_active_enrollment_registration_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="registration_payment_submitted",
            field=models.BooleanField(
                default=False, verbose_name="کد پیگیری پرداخت ارسال شد"
            ),
        ),
    ]
