# Generated by Django 6.0.6 on 2026-08-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='مدرک نهایی'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signatures/', verbose_name='عکس امضا')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='core.student')),
            ],
        ),
    ]
