# Generated by Django 6.0.6 on 2026-09-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_enrollment_registration_payment_submitted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "code",
                    models.CharField(
                        help_text="فقط حروف انگلیسی و عدد. مثلاً: ali یا insta-campaign",
                        max_length=30,
                        unique=True,
                        verbose_name="کد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "منبع معرفی",
                "verbose_name_plural": "منابع معرفی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="referral_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="core.referralsource",
                verbose_name="منبع معرفی",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="core.referralsource",
                verbose_name="معرف",
            ),
        ),
    ]
