# Generated by Django 6.0.6 on 2026-09-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_referralsource_enrollment_referral_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="certificate_file",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_certified",
        ),
    ]
