# Generated by Django 6.0.6 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_student_certificate_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcamp",
            name="remaining_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ظرفیت ثبت\u200cنام باقیمانده"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کدملی"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_code__isnull", False)),
                fields=("national_code",),
                name="unique_national_code_when_set",
            ),
        ),
    ]
