# Generated by Django 6.0.6 on 2026-09-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_bootcamp_remaining_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_national_code_when_set",
        ),
    ]
