# Generated by Django 6.0.6 on 2026-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_student_unique_national_code_when_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=7,
                null=True,
                unique=True,
                verbose_name="کد رهگیری مدرک",
            ),
        ),
    ]
