# Generated by Django 6.0.6 on 2026-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_enrollment_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="bale_group_url",
            field=models.URLField(
                blank=True,
                help_text="لینک دعوت گروه پشتیبانی بله این دوره",
                null=True,
                verbose_name="لینک گروه بله",
            ),
        ),
        migrations.AddField(
            model_name="bootcamp",
            name="telegram_group_url",
            field=models.URLField(
                blank=True,
                help_text="لینک دعوت گروه پشتیبانی تلگرام این دوره",
                null=True,
                verbose_name="لینک گروه تلگرام",
            ),
        ),
    ]
